apiVersion: apps/v1
kind: Deployment
metadata:
  name: ev-charging-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ev-charging-app
  template:
    metadata:
      labels:
        app: ev-charging-app
    spec:
      containers:
      - name: ev-charging-app
        image: 172103/ev-charging-app:latest  # Correctly tagged image
        ports:
        - containerPort: 8501
        resources:
          limits:
            memory: "512Mi"
            cpu: "1"
          requests:
            memory: "256Mi"
            cpu: "0.5"
